### ISSUE TITLE
如何设置上传的分块

### ISSUE THREAD

**Issue by waitsaber** [ZhangMingZhao1/StreamerHelper#100]
我的是国外的vps 千兆带宽 今天测试了下 600多MB的文件被分成了131块，出方向的流量经常不动，不知道是不是分块数太多导致的，想修改下分块数量试试看。
![图片](https://user-images.githubusercontent.com/67093172/121792154-003fc400-cc24-11eb-8730-a1db93bfbd8e.png)
![图片](https://user-images.githubusercontent.com/67093172/121792161-0fbf0d00-cc24-11eb-88ea-4221778d678c.png)

**Comment by waitsaber** [comment]
经常时候上传上传着就报错，然后又重新进行上传。
![图片](https://user-images.githubusercontent.com/67093172/121792204-84924700-cc24-11eb-9364-bd1e506f13e3.png)

**Comment by umuoy1** [comment]
分块数量是根据`⌈文件大小/每块大小⌉`确定的，无法直接配置，但可以直接修改代码[https://github.com/ZhangMingZhao1/StreamerHelper/blob/master/src/uploader/index.ts#L302](url)。

**Comment by CuteLuoBo** [comment]
遇到了相同问题，之前使用国内的服务器可以正常上传，近期切换使用香港的服务器之后，就开始出现如类似情况，上传到随机区块后，上传相关的信息输出中止，也没有报错信息。到下个上传检查周期之后，又从头开始上传：
![_DQD4_Y~K@$_ZXEXG1@(`L4](https://user-images.githubusercontent.com/44561136/130016736-65ec31c7-86ae-4cb0-b60d-682962e21825.png)

![`7QB){{ A69ZS~%9DW6C_EK](https://user-images.githubusercontent.com/44561136/130016687-a0b46b7c-5aee-4d4c-8eca-d3ec49efd46b.png)
