### ISSUE TITLE
bilibili投稿入口升级中，投稿失败

### ISSUE THREAD

**Issue by storyxc** [ZhangMingZhao1/StreamerHelper#108]
[2021-07-10T14:57:46.907] [ERROR] recycleFile - Upload fails, returns:, 21150 message 投稿入口升级中，请重新编辑稿件 ttl
 1 aid 0 bvid xxxxx

**Comment by gitiray** [comment]
同，前些天还是正常的，昨天上传就出错了。
另外，在有报错的情况下，文件依然被标记为 succeedUpload，还好及时发现，得到挽救。
```
[ERROR] recycleFile - Upload fails, returns:, 21150 message 投稿入口升级中，请重新编辑稿件 ttl 1 aid 0 bvid xxxxx
```
