### ISSUE TITLE
【建议】希望可以增加一些文本占位符

### ISSUE THREAD

**Issue by CuteLuoBo** [ZhangMingZhao1/StreamerHelper#114]
编辑标题/描述/动态信息的时候感觉限制太大了，要么选择默认的格式，要么只能完全固定，后期还需要手动调整

建议增加一些占位符便于自行搭配格式，例如：直播间地址/主播名/录制时间/开播时间/最后结束录制时间这类

**Comment by umuoy1** [comment]
会在下次更新中考虑加入
