### ISSUE TITLE
【建议】希望增加 Server酱 Turbo推送

### ISSUE THREAD

**Issue by HNDXlsp** [ZhangMingZhao1/StreamerHelper#131]
建议增加server酱用来推送 上传成功/失败 等稿件信息，以及程序的ERROR级报错日志。

**Comment by HNDXlsp** [comment]
好耶

**Comment by gitiray** [comment]
Server Turbo 免费用户每天只有5条额度，可能会不够用
建议加上 [PushPlus ](https://pushplus.plus/)和 [Telegram](https://core.telegram.org/bots/api#authorizing-your-bot)
