### ISSUE TITLE
斗鱼的录制提示正在检查直播

### ISSUE THREAD

**Issue by 5icorgi** [ZhangMingZhao1/StreamerHelper#147]
配置了B站的直播录制正常，配置了斗鱼的直播提示`[2022-04-10T23:00:21.238] [INFO] checkRoom - 正在检查直播 咻咻满 https://www.douyu.com/8777`就没有其他提示，并且主播也是在直播状态的，换了几个斗鱼主播都是这个提醒。

**Comment by 150481878** [comment]
> 
准确来说应该是女主播，我试了游戏主播没问题，女主播就不识别

**Comment by spitir** [comment]
很神奇
