### ISSUE TITLE
 An error occurred when try to check token: Error: getaddrinfo EAI_AGAIN api.snm0516.aisee.tv

### ISSUE THREAD

**Issue by 374857922** [ZhangMingZhao1/StreamerHelper#151]
An error occurred when try to check token: Error: getaddrinfo EAI_AGAIN api.snm0516.aisee.tv

**Comment by 374857922** [comment]
token获取不到报错阿？咋整

**Comment by spitir** [comment]
那就获取啊！https://github.com/ForgQi/biliup-app 用这个可能简单点
