### ISSUE TITLE
Windows部署的，有点问题不是很懂，请教一下。

### ISSUE THREAD

**Issue by LucasJX** [ZhangMingZhao1/StreamerHelper#158]
![微信图片_20220525152003](https://user-images.githubusercontent.com/50724432/170210696-d85c1ca6-437b-4595-891a-603ff358bf07.png)
nvm 和 Node.js ;FFmpeg 全部都能正常显示，成功安装。

**Comment by umuoy1** [comment]
`npm run dev`看下能不能跑

**Comment by umuoy1** [comment]
没有创建配置文件，请根据https://github.com/ZhangMingZhao1/StreamerHelper#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE

**Comment by LucasJX** [comment]
windows的默认配置是在StreamerHelper\templates里面的info-example.json文件吗？
