### ISSUE TITLE
奇怪的不会自动录制BUG

### ISSUE THREAD

**Issue by BCYDTZ** [ZhangMingZhao1/StreamerHelper#167]
开启软件时如果主播没有直播，但是软件会建立主播时间文件夹，然后后面主播直播了，但是多次检测到以后，软件不会录制，但是我把建立的主播时间文件夹删除以后，过几分钟它检测到了，就开始录制了。
INFO] Recorder Boboo 波波欧尼 - 下载流 Boboo 波波欧尼 退出，退出码: 1

**Comment by SouLXH** [comment]
这个问题 现在还存在
