### ISSUE TITLE
扫码无法登录B站

### ISSUE THREAD

**Issue by Cicaba** [ZhangMingZhao1/StreamerHelper#177]
█ ▄▄▄▄▄ █  ▀█▀█▄▄▄ ▄▀█▀▄▄█  ▄ ▀ ▀▀█ ▄▄▄▄▄ █
█ █   █ █ █▀▄▀▄▀ █▀▀▀▀▄▀█▄▀▄█▀▄▄▄██ █   █ █
█ █▄▄▄█ █▀▀ █▄ ▄█▀ ▄ ▄▀▄▄█▀█▄▄▄▀▀██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█▄█ ▀ ▀▄█▄▀ ▀▄█ ▀ ▀ ▀ █▄▄▄▄▄▄▄█
█ ▄██▄ ▄█▀ ▀█ ▀ ▀▀▄ ▄▄▄ ▀▄▀ ▀▀▄▀▄▄▀▀ ▀▄ ▄ █
█▀██ ▀█▄ ▀█▄▀ █▀▄█ ▀▀  ▄ ███▄▀▀ ▀▀  ▀█▀██▄█
█▄█ ██ ▄ ▄▄██▄▄▄▄▀▀▄ ▄██▀▄█▄▀▄ ▀█▀▀▀▄▀▀▀  █
███▄▀▀▀▄█▄▄██▀▄ █▄▀  ▀ ▀▄█▄    ▄▀▄▄▄██ ▄▀ █
█▄  █▀▀▄▀▄ ▄ ██▀ ▀ ▀█▄ █▀█▀█▀▀▄▀▄  ▀▀▀ ▀ ██
█▄▀▄▀▀▄▄▀▀█▀ ▄ ▄▄▀█▄▀ █▀▄▄██▄▄▀▄█▀█  █▀█▀ █
█ █ ▄▀▄▄▀██ █▀ ▀█▄▀▀▀▀▀▄▀▄█▄ ▄ ▄▄▄▀▀▄▀██▀ █
█▀█ ▄ ▄▄ ▀ ▀ ▄█▀ ▀ ██▄ █▄▀██   ▀▀▀▄▄█▄ ▄▀ █
█▄▄▀ █▀▄█  █▀▄▀█▀▀▄▄▄▄▄ ▀█▀ ▀█ ▀▄█ ▀ ▀ ▀█ █
█▄█▄█ ▀▄▄▄█▀▄ █▀▄  ▀█▀ ▄▄▄█  ▀ █▀█▄▀█ ▄▄▀ █
█ █▄ █▄▄  ██▄▄ ▄█▀█▄▀▄█▀▀▄█▄ ▄▄▄▄▄▀▀▄▀█▀▄▀█
███▀ ▀▄▄▄ ▄██▀█ █▄   ▀ ▀▄▀▄ ▄▄▀███  █▀▀██▄█
█▄▄▄█▄█▄█▀▄▀ ▀██    █▄  ▀█▀█▀▀▄▀█ ▄▄▄  █▀ █
█ ▄▄▄▄▄ █▀█  █ ▄ ▀█▄█ █▀ ▄██ ▄ ▀  █▄█ █▄█ █
█ █   █ █▄▀▀▄▀ ▀█▄▀▀▀▀█▄▀▀▀▄ ▄ ▄▄▄ ▄▄▄▄▀▄▀█
█ █▄▄▄█ █▀▀▄ ▄█▄ ▀▀ █▄▀▀▄ ██▄█ ▀   ▀▄▀▄█▀ █
█▄▄▄▄▄▄▄█▄███▄███▄▄█▄▄▄██▄████▄█▄▄██▄███▄██

[2023-01-05T10:01:31.697] [INFO] User - LOGIN BY QRCODE SUCCESS
[2023-01-05T10:01:31.699] [INFO] User - Check token a20b6137cd210365f523d0e4b********

[2023-01-05T10:01:31.947] [ERROR] User - An error occurred when try to auth by access_token: 账号未登录
[2023-01-05T10:01:31.948] [ERROR] APP - undefined

**Comment by mzzgaopeng** [comment]
同

**Comment by songyaolun** [comment]
同样的问题
