### ISSUE TITLE
Windows部署npm run serve失败

### ISSUE THREAD

**Issue by aYu-asd** [ZhangMingZhao1/StreamerHelper#183]
node版本18.17.0
ffmpeg配了环境变量
PM2已安装
![image](https://github.com/ZhangMingZhao1/StreamerHelper/assets/112919747/f9bfc75c-3904-4cae-9496-ad8f1fda48a3)

**Comment by Xbai-hang** [comment]
试试 `node 16`，并且执行：`npm install @types/node@16 --save-dev`

**Comment by umuoy1** [comment]
fix at #196
