### ISSUE TITLE
B站直播流收取失败

### ISSUE THREAD

**Issue by yesmiley** [ZhangMingZhao1/StreamerHelper#36]
download 文件夹中全是几十B的文件碎片，无法播放

log 无限循环:
```
开始下载 --> 子进程退出，退出码 1 --> 断流，但直播间仍在线，继续下载
```

**Comment by ZhangMingZhao1** [comment]
我们这里本地好像没问题，是最新代码吗

**Comment by yesmiley** [comment]
是最新代码，运行在腾讯云轻量
同时使用其它开源项目能够正常录制（应该可以排除IP被屏蔽的问题）
甚至还开了另一台VPS也是一样的情况：本项目不能，另一个可以。
看了下源码，这边用的是H5接口，输出的是M3U8，甚至在我本地电脑上都有拉流失败的问题。另一个项目用的则是WEB接口，直接输出FLV。

**Comment by ni00** [comment]
![1](https://user-images.githubusercontent.com/56543214/89006692-e104b480-d339-11ea-8189-8c93e0341cdd.jpg)
![2](https://user-images.githubusercontent.com/56543214/89006699-e4983b80-d339-11ea-97e0-d4f5e7bb9246.png)
我这儿录制B站直播流是成功的，我测试了三个房间，全部录制成功并且能正常播放。你能把你录制的房间发我一下吗？

**Comment by ni00** [comment]
发一下ffmpeg版本号？

**Comment by yesmiley** [comment]
现在试了下又正常了……额，时好时坏的样子，不知道是不是B站的问题，我再观望一下吧先

**Comment by Airmole** [comment]
我也遇到这个问题了
