### ISSUE TITLE
最近投稿老是提示转码失败

### ISSUE THREAD

**Issue by daofeng2015** [ZhangMingZhao1/StreamerHelper#47]
![image](https://user-images.githubusercontent.com/14891398/90982119-a76d4500-e597-11ea-9af8-2197232b4449.png)
不知道是不是ffmpeg拉流的参数有问题

**Comment by umuoy1** [comment]
流的原因，直播刚开始流可能不稳定，删掉第一P就好了。

**Comment by zazaluMonster** [comment]
目前还是会出现转码失败的情况，b站

**Comment by it985** [comment]
现在依然存在转码失败
![image](https://user-images.githubusercontent.com/62421120/205552915-1141beac-a421-481f-bc3a-9d0148966702.png)
