### ISSUE TITLE
直播源获取api参考

### ISSUE THREAD

**Issue by dfaofeng** [ZhangMingZhao1/StreamerHelper#51]
虎牙直播
get请求 https://mp.huya.com/cache.php?m=Live&do=profileRoom&pid=311913984  311913984为房间id

龙珠直播
get请求 https://livestream.longzhu.com/live/getlivePlayurl?roomId=2183764   2183764为房间id

**Comment by ZhangMingZhao1** [comment]
感谢，这是哪个平台提供的接口

**Comment by daofeng2015** [comment]
> 感谢，这是哪个平台提供的接口

微信小程序抓的
