### ISSUE TITLE
会出现部分投稿卡审核

### ISSUE THREAD

**Issue by zazaluMonster** [ZhangMingZhao1/StreamerHelper#66]
首先非常感谢编写此项目的大佬们！让我可以非常简单的做到自动录播自动投稿！

在接近快半个月的使用情况下来后，我发现15天里有2天的投稿是一直处于卡审核的状态（不是审核不通过，状态一直是审核中）

想问下有没有人和我遇到类似情况。

后续是否可以增加一个开关，支持保留文件！ 因为这样如果遇到卡审核的情况，可以重新投一下呢

**Comment by umuoy1** [comment]
#62 增加了选项，可以不删除本地文件

**Comment by leecoooo** [comment]
不删除本地文件我发现有个问题，如果一个主播每天开播多次，后面一次会把前面的录像也一起上传

卡审核的原因是转码失败，我问过客服了
