### ISSUE TITLE
能否提升稳定性+加入网页面板

### ISSUE THREAD

**Issue by older-fox** [ZhangMingZhao1/StreamerHelper#67]
烦请参考
https://github.com/hr3lxphr6j/bililive-go

另，有可能出现上传不完整及分段失败。

**Comment by ZhangMingZhao1** [comment]
StreamHelper的定位是配好config信息后，跑在服务器的后台，所以不需要可视化面板。。。以前做过本地的客户端形式感觉用处不大。。上传不完整这种很难定位，也在慢慢排查中。

**Comment by WTFTWTM** [comment]
能否将log信息输出到前台,不然pm2中空空荡荡连在干啥都不知道...

**Comment by ZhangMingZhao1** [comment]
是指pm2的log信息？

**Comment by WTFTWTM** [comment]
yeah
