### ISSUE TITLE
请问除了todo list里支持的一些国内平台，是否也支持twitcast的录制呢？

### ISSUE THREAD

**Issue by Richardhzj** [ZhangMingZhao1/StreamerHelper#68]

**Comment by Richardhzj** [comment]
我已经把代码下载下来准备运行了，有一个额外的问题，我只有在cookies里看到类似DedeUserID的参数，但是配置项里可选的access_token这个应该在哪里获取到呢？

如果获取到了这个token，大概过期时间会是多久呢？会不会输入后到时过期了反而导致无法登录上。

如果程序放在Linux服务器上一直运行着，为什么会出现你在readme上描述的“频繁登录”从而造成证码登录的问题呢

**Comment by umuoy1** [comment]
未支持，你可以提个pr
