### ISSUE TITLE
怎样修改原创和禁止转载

### ISSUE THREAD

**Issue by miku8311** [ZhangMingZhao1/StreamerHelper#74]
大佬 如题 文件看了好多 不知道改哪个

**Comment by AronWater** [comment]
没懂   请问你这问题能给多一点资料或者例子吗

**Comment by miku8311** [comment]
这个问题已经搞懂了 现在又出现一个新的问题
![Screenshot_20210125_025454](https://user-images.githubusercontent.com/62003212/105640392-bf375500-5eb8-11eb-99fe-1b5ca2cdee50.jpg)

**Comment by miku8311** [comment]
转码失败是什么造成的 数据过大还是什么原因

**Comment by AronWater** [comment]
和issue标题无关的 新开一个issue比较好 。时间戳问题可能有很多原因，有可能是码率问题 你可以检查一下mediainfo总时间 和 视频本应时常多少 比较一下   。
还有别人问你 ，最好给一下回应 ，而不是无视别人说已经解决了，  然后又抛一个新的问题  ， 当然我只是个人感觉这样有礼貌一点。
