### ISSUE TITLE
关于docker安装配置的问题

### ISSUE THREAD

**Issue by leecoooo** [ZhangMingZhao1/StreamerHelper#78]
能不能具体说下这个docker是怎么build的？我想在群晖上的内置docker里面装

**Comment by leecoooo** [comment]
研究了下

在群晖的 SSH 进入 StreamerHelper 文件夹
然后先 build
docker build -t stream:v1 .

再运行容器
docker run --name stream -itd -v /volume1/docker/StreamerHelper/templates/info.json:/app/templates/info.json -v /volume1/docker/StreamerHelper/download:/app/download --dns 114.114.114.114 --restart always stream:v1

**Comment by zsnmwy** [comment]
不需要build。
原有指南中的镜像，已经支持了 ARM以及 X86。
只需要挂载需要的目录到对应的位置即可。

**Comment by leecoooo** [comment]
> 不需要build。
> 原有指南中的镜像，已经支持了 ARM以及 X86。
> 只需要挂载需要的目录到对应的位置即可。

懂了，谢谢说明

**Comment by leecoooo** [comment]
群晖不行，一定要有镜像在本地，还是需要build一次。
估计跟群晖自带的docker相性不太合，录制时疯狂中断，分了几十p。

**Comment by zsnmwy** [comment]
> 群晖不行，一定要有镜像在本地，还是需要build一次。
> 估计跟群晖自带的docker相性不太合，录制时疯狂中断，分了几十p。

与群晖无关。项目bug。
