### ISSUE TITLE
支持腾讯云开发一键部署

### ISSUE THREAD

**Issue by binggg** [ZhangMingZhao1/StreamerHelper#81]
可以基于云开发的 Serverless 容器来部署，考虑在文档中加一个一键部署按钮，方便大家部署体验

https://docs.cloudbase.net/framework/guide/container-app.html

**Comment by zsnmwy** [comment]
看了一下文档，感觉问题不大。
问题腾讯云的资费这么高，真的有人用吗？

**Comment by binggg** [comment]
这个是设置缩容到 0 的，还挺多人用的
