### ISSUE TITLE
容器重启时候会重新上传录播文件夹下面所有文件夹

### ISSUE THREAD

**Issue by leecoooo** [ZhangMingZhao1/StreamerHelper#82]
我选择了保存录播文件，重启了容器后又把全部文件夹重新传了一遍，包括了那些已经重命名为xxx-intermediate-xxx的文件夹也上传了。

**Comment by zsnmwy** [comment]
因为容器的构建是关联到我fork之后的项目。
所以会导致主项目更新之后，我的容器镜像不一定会跟着更新。
现在我的master分支已经跟主项目同步。

可以尝试重新拉取镜像，再次运行。

~不包好用~

**Comment by leecoooo** [comment]
正常安装也会，pm2 restart app之后也会重新上传所有录播文件夹，应该是bug

**Comment by ZhangMingZhao1** [comment]
> 正常安装也会，pm2 restart app之后也会重新上传所有录播文件夹，应该是bug

#79 这个现象是是这个pr提供的feature展现的正常功能，上传的视频上传成功后会自动删除，留下的视频肯定是失败的，那么这个pr原本是想重启后重新上传这些失败的视频

**Comment by zsnmwy** [comment]
我已经在重构了。
重构的版本已经尽量避免重传问题以及支持分片重传。
再等等吧=。=
