### ISSUE TITLE
有考虑加入弹幕录制功能及弹幕压制功能吗？

### ISSUE THREAD

**Issue by leecoooo** [ZhangMingZhao1/StreamerHelper#83]
同步录制弹幕文件，下播后自动把 xml 弹幕转换为 ass ，然后压制成弹幕版录播视频再上传。

请问有可能实现吗？

**Comment by zsnmwy** [comment]
使用隔壁的[录播姬](https://rec.danmuji.org/docs/desktop/danmaku/)可能会更加适合你。

可以实现，但不会优先处理。
