### ISSUE TITLE
建议收到退出码后延时检查一下直播间状态再上传。

### ISSUE THREAD

**Issue by leecoooo** [ZhangMingZhao1/StreamerHelper#92]
我这边经常出现主播稍微卡顿一下就触发上传流程，实际并没有下播。建议上传之前延迟10秒左右检查一下直播间状态，如果是下播状态再传。

**Comment by umuoy1** [comment]
现在下载和上传是分开检测的，可以考虑将`roomCheckTime`设短，`recycleCheckTime`设长
