### ISSUE TITLE
当主播仍在直播时，就会开始上传视频并投稿，时间都是10分钟左右很短的时长

### ISSUE THREAD

**Issue by zazaluMonster** [ZhangMingZhao1/StreamerHelper#96]
首先感谢大佬们的这个项目，让我可以解放双手！
在比较良好的使用体验过程中，最近经常遇到一种情况：“当主播仍在直播时，就会开始上传视频并投稿，时间都是10分钟左右很短的时长”
这样导致录播投稿会很散，有点困扰
机子是ubuntu18.04，带宽是5M的
希望可以帮忙解答下疑惑！

**Comment by umuoy1** [comment]
初步考虑是FFmpeg的问题，目前正考虑使用更稳定的下载方式
